#!/usr/bin/env python3
"""Audit author-provided GSE214611 metadata for the border-zone project.

The goal is to verify that the downloaded metadata can support the first
prototype before we fetch heavier expression matrices.
"""

from __future__ import annotations

import csv
from collections import Counter, defaultdict
from pathlib import Path

from project_paths import project_root


ROOT = project_root(__file__)
METADATA_DIR = ROOT / "data" / "metadata" / "gse214611_author"
OUT_DIR = ROOT / "results" / "tables"

SPATIAL_METADATA = METADATA_DIR / "spatial_object_integrated_metadata.csv"
SN_METADATA = METADATA_DIR / "sn_wc_object_integrated_metadata.csv"

SPATIAL_SCORE_COLUMNS = [
    "BZ1_genes",
    "BZ2_genes",
    "RZ_genes",
    "X33_Fib_Postn",
    "X36_Fib_Rep",
    "X31_Fib_Pi16",
    "X11_Monos",
    "X14_Mac_C1qa",
    "CM_Score",
]


def read_rows(path: Path) -> tuple[list[str], list[dict[str, str]]]:
    with path.open(newline="") as handle:
        reader = csv.DictReader(handle)
        rows = list(reader)
        return list(reader.fieldnames or []), rows


def safe_float(value: str) -> float | None:
    try:
        if value == "":
            return None
        return float(value)
    except ValueError:
        return None


def write_counter(path: Path, counter: Counter[str], label: str) -> None:
    with path.open("w", newline="") as handle:
        writer = csv.writer(handle, delimiter="\t")
        writer.writerow([label, "n"])
        for key, n in counter.most_common():
            writer.writerow([key, n])


def summarize_scores(
    rows: list[dict[str, str]],
    group_columns: list[str],
    score_columns: list[str],
    out_path: Path,
) -> None:
    sums: dict[tuple[str, ...], dict[str, float]] = defaultdict(lambda: defaultdict(float))
    counts: dict[tuple[str, ...], dict[str, int]] = defaultdict(lambda: defaultdict(int))
    group_n: Counter[tuple[str, ...]] = Counter()

    for row in rows:
        key = tuple(row.get(col, "") for col in group_columns)
        group_n[key] += 1
        for col in score_columns:
            value = safe_float(row.get(col, ""))
            if value is None:
                continue
            sums[key][col] += value
            counts[key][col] += 1

    with out_path.open("w", newline="") as handle:
        writer = csv.writer(handle, delimiter="\t")
        writer.writerow([*group_columns, "n_spots", *[f"mean_{col}" for col in score_columns]])
        for key, n in group_n.most_common():
            means = []
            for col in score_columns:
                denom = counts[key][col]
                means.append("" if denom == 0 else f"{sums[key][col] / denom:.6g}")
            writer.writerow([*key, n, *means])


def write_markdown_summary(
    spatial_columns: list[str],
    spatial_rows: list[dict[str, str]],
    sn_columns: list[str],
    sn_rows: list[dict[str, str]],
    out_path: Path,
) -> None:
    spatial_orig = Counter(row["orig.ident"] for row in spatial_rows)
    spatial_annot = Counter(row.get("annotated", "") for row in spatial_rows)
    sn_sample = Counter(row.get("sample", "") for row in sn_rows)
    sn_cluster = Counter(row.get("final_cluster", "") for row in sn_rows)

    lines = [
        "# GSE214611 Metadata Audit",
        "",
        "Generated by `scripts/audit_gse214611_metadata.py`.",
        "",
        "## Files",
        "",
        f"- Spatial metadata: `{SPATIAL_METADATA}`",
        f"- Single-nucleus/whole-cell metadata: `{SN_METADATA}`",
        "",
        "## Basic Shape",
        "",
        f"- Spatial rows: {len(spatial_rows):,}",
        f"- Spatial columns: {len(spatial_columns):,}",
        f"- Single-nucleus/whole-cell rows: {len(sn_rows):,}",
        f"- Single-nucleus/whole-cell columns: {len(sn_columns):,}",
        "",
        "## Key Spatial Columns Present",
        "",
    ]

    for col in SPATIAL_SCORE_COLUMNS:
        lines.append(f"- `{col}`: {'yes' if col in spatial_columns else 'no'}")

    lines.extend(
        [
            "",
            "## Top Spatial Samples",
            "",
            "| orig.ident | n |",
            "|---|---:|",
        ]
    )
    for key, n in spatial_orig.most_common(10):
        lines.append(f"| {key} | {n} |")

    lines.extend(
        [
            "",
            "## Spatial Annotated Domains",
            "",
            "| annotated | n |",
            "|---|---:|",
        ]
    )
    for key, n in spatial_annot.most_common():
        lines.append(f"| {key} | {n} |")

    lines.extend(
        [
            "",
            "## Top Single-Nucleus/Whole-Cell Samples",
            "",
            "| sample | n |",
            "|---|---:|",
        ]
    )
    for key, n in sn_sample.most_common(10):
        lines.append(f"| {key} | {n} |")

    lines.extend(
        [
            "",
            "## Top Cell/Nucleus Clusters",
            "",
            "| final_cluster | n |",
            "|---|---:|",
        ]
    )
    for key, n in sn_cluster.most_common(15):
        lines.append(f"| {key} | {n} |")

    lines.extend(
        [
            "",
            "## Output Tables",
            "",
            "- `results/tables/gse214611_spatial_scores_by_sample.tsv`",
            "- `results/tables/gse214611_spatial_scores_by_sample_annotated.tsv`",
            "- `results/tables/gse214611_sn_clusters.tsv`",
            "",
            "## Interpretation",
            "",
            "The author metadata already contains BZ gene scores, deconvolved fibroblast/myeloid-like scores, domain labels, and sample identifiers. This is sufficient for a first-pass prototype of the border-zone risk score before downloading heavier expression matrices.",
        ]
    )

    out_path.write_text("\n".join(lines) + "\n")


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    spatial_columns, spatial_rows = read_rows(SPATIAL_METADATA)
    sn_columns, sn_rows = read_rows(SN_METADATA)

    summarize_scores(
        spatial_rows,
        ["orig.ident"],
        [col for col in SPATIAL_SCORE_COLUMNS if col in spatial_columns],
        OUT_DIR / "gse214611_spatial_scores_by_sample.tsv",
    )
    summarize_scores(
        spatial_rows,
        ["orig.ident", "annotated"],
        [col for col in SPATIAL_SCORE_COLUMNS if col in spatial_columns],
        OUT_DIR / "gse214611_spatial_scores_by_sample_annotated.tsv",
    )
    write_counter(
        OUT_DIR / "gse214611_sn_clusters.tsv",
        Counter(row.get("final_cluster", "") for row in sn_rows),
        "final_cluster",
    )
    write_markdown_summary(
        spatial_columns,
        spatial_rows,
        sn_columns,
        sn_rows,
        OUT_DIR / "gse214611_metadata_audit.md",
    )


if __name__ == "__main__":
    main()
